### ISSUE TITLE
Page 98 problems - Post story to Instagram

### ISSUE THREAD

**Issue by elsatch** [yasoob/practical-python-projects#3]
Hi,

I have just purchased the book and this is my initial feedback. I was quite interested on the chapter about automatic summarization and automated image generation. After reading the description of the book and the table of contents I decided to buy it. The end of that chapter and, specially page 98, breaks all the promises of the book In less than one A4!

This book is end-to-end Python projects for intermediate Python programmers but...

- Section called Posting Stories to Instagram is just: Oh no, this goes against Instagram TOS so go and find a library on Github to do it. I won’t tell you how to do it. It’s like in the Steam chapter you started by saying: "In this chapter we will parse Steam content using lxml, but given it goes against TOS... all these sections are left as an exercise to the reader!"

- Section Troubleshooting is just: if it breaks, there is a search engine called Google where you can paste the error. Then you will find some links to Stack Overflow and usually answer is there... Is this real advice for intermediate Python programmers?

- Let’s go back to the top of the page 98: resolution of these images is quite poor. RTFM and find the solution.

To me this whole page is an absolute mess! No end-to-end solutions, not tailored to intermediate programmer at all.

Potential fixes:
- Propose a service to publish stories to Instagram that has an active API. Maybe Later/Buffer/Hootsuite allow you to publish some stories using a trial. Show how to do it using the given API.

- Create the images for any other service that allows to to publish pictures: Images to go along a Twitter post, images for a Facebook post, thumbnails for Youtube, thumbnails for Twitch, thumbnails for a meetup event, pictures for a TikTok post, Pictures for Pinterest... there are dozens of social networks that allow you to put the content on an automated way without breaking TOS. If Instagram doesn’t, then maybe it’s not a good choice for this chapter.

I will take a look to the other chapters regarding the troubleshooting aspects, to see if this is the common response or if this is an exception.

**Comment by yasoob** [comment]
Hi @elsatch,

Thank you so much for the feedback. I hear your concerns regarding posting on Instagram. I originally had a section in that chapter that made use of [Instagram-API-Python](https://github.com/yasoob/Instagram-API-python) and actually showed how to post to Instagram. Two days before the release of the book, the original project from GitHub got removed. We removed that section from the book because of that and replaced it with this text. I might upload the Instagram upload part on my blog and link to that in the book. 

As for image resolution on page 98, I have given an explanation in the same chapter as to why the resolution is poor. It is because we extract images from a live article and crop them into two separate images. If the original image is of low quality then the cropped ones are by default going to be of low quality. I think we can do a better job and probably use a different article that has higher quality pics. I will work on that for the next iteration of book updates.

Regarding your critique of Troubleshooting section, for each chapter I tried to add whatever potential issues (and fixes) I could think of. Most of the chapters give targeted troubleshooting advice. If any chapter says that just use Google, it is because I couldn't foresee any major issues cropping up while working on the project. If you come across any issue that is not covered in the troubleshooting section please let me know via this issue tracker and I will be happy to add that to the book!

I would really appreciate it if you could look at other chapters as well. Some of the issues you mentioned are exceptions. After all, this is the alpha version and we were expecting some things to break. We will fix them as soon as we can and will send out an update.

Have a wonderful day!

~ Yasoob

**Comment by elsatch** [comment]
Thanks for your prompt reply! I will check other chapters and Ofer any potential constructive feedback!

Have a nice day too!

César

**Comment by yasoob** [comment]
I have updated the article summarization chapter to include more details. I also posted the redacted part (Instagram uploading) online [on my blog](https://yasoob.me/posts/using-python-to-post-stories-on-instagram/) and linked to it in the chapter. If you still find any issues feel free to post them here or send me an email :) 

The latest version with the fixes will be sent out later today.
